### ISSUE TITLE
Hate to Spread Negativity 

### ISSUE THREAD

**Issue by Librechain** [AlphaWallet/TokenScript-Examples#152]
I think that the concept behind 'TokenScript' is honestly one of the most redundant, useless ideas I've seen that also has **so much effort behind it in terms of development**. 

That's my honest assessment. I'm not saying this to cut the project down even though that's exactly what this message does. I just want to provide my feedback because I feel like nobody else has ever said that to you guys before and this is how I genuinely feel. 

### You All are Talented and Needed Though 

This feedback doesn't mean you guys aren't brilliant. What you did with AlphaWallet is absolutely superb and this space will forever remain indebted to you all for it. 

My dream is to revisit this project / entity behind both 'TokenScript' & AlphaWallet and find that you all have re-shifted focus and decided to put all of your energies behind the direction pursued by AlphaWallet. 

That's not an order. You don't have to listen to me and I don't expect you to. My criticism is going to sound biting, but its an honest opinion.

**Comment by SmartLayer** [comment]
Thanks for the feedback! To be honest, I ask myself this question once in a while. (And I've been with this project since its beginning!) I wish to dissect this with you. Which one of the following is closest to your view?

1. The vision that future web3 is decentralised thanks to tokens as trust anchors is implausible or undesirable†
2. The mechanism to reach that vision, that web3 websites run code from multiple tokens of different domains and work together‡, is not attenable
3. The above mechanism is attenable through a token oriented architect not based on the blockchain as known today
4. The above is attainable through Blockchain, but you are making it wrong.

> † by *undesirable* I mean "if Google/Facebook etc trust anchor role is replaced by tokens, it leads to an evolutionary deadend", not "Facebook/Google will not want to buy or use your tech".
> ‡ Compared to today, websites run components of the same domain, that is the same group of people responsible for the outcome - I use the word multi-domain to refer to group of builders with different interests, such as car-vendor vs car-rental market operator.

This effort to dissect a seemly simple statement ("guys you are wasting your time") is because the outcomes are different. If 1 or 2 is ultimately true, we better close the project or the company, as the implied requirements for any tokenisation tech (T.I.P.S.) is based on the premises denied by 1 or 2. If 3 is true, we showed up at the wrong time and should go to academic research. If 4 is true, we still have time to pivot.

Wrong or not, we never were/will be at a point we can claim, "we are fine, and we don't need your help/advice".

**Comment by JeanLeeJeffrson** [comment]
Je to konec cesty
