### ISSUE TITLE
Schema 2020/03 needs to allow specifying whether an event's parameter is indexed

### ISSUE THREAD

**Issue by hboon** [AlphaWallet/TokenScript-Examples#29]
This is necessary so we can form the RPC payload for event filtering. In the Etherenm node RPC call, the filter part of the payload is a sequence based only by the indexed parameters, not  key-value pairs.

https://github.com/AlphaWallet/TokenScript-Examples/blob/master/examples/ENS/ENS.xml#L32

Something to this effect:

```
    <asnx:module name="NameRegistered">
      <sequence>
        <element name="name" ethereum-type="string"/>
        <element name="label" ethereum-type="bytes32" indexed=true/>
        <element name="owner" ethereum-type="address" indexed=true/>
        <element name="cost" ethereum-type="uint"/>
        <element name="expires" ethereum-type="uint"/>
      </sequence>
    </asnx:module>
```

(but then, maybe that implies heavily that the module is ethereum-based?)

**Comment by colourful-land** [comment]
To demonstrate the problem, with the definition @hboon suggested, If we filter by label=1, that part of the payload sent via RPC is roughly:
````
[
1, //for label
nil, //for owner. but looks like trailing nils are optional
]
````
Notice that "name" is skipped, it is not:
````
[
nil, //name
1, //label
nil, //owner
]
````

**Comment by colourful-land** [comment]
Please use `upgrade-schema-2020-03` branch in `TokenScript-Examples` repo, where the requested attribute is added. Note that in order to validate the tokenscript (should you want to do so), use the `schema/2020/03` branch of `TokenScript` repo which has the schema.

Note that I changed `ethereum-type` to `ethereum:type` in the source code. Be mindful of the namespace. Thanks.
